name: PhantasyStatus
version: ${project.version}
main: hugu1026.com.github.phantasystatus.PhantasyStatus
commands:
  st:
    description: "Open Status Setting Gui."
  myst:
    description: "Show your status."
  setmagiclimit:
    description: "Set player's magic limit."
  giveexp:
    description: "Give player specific exp"
